---
- hosts: webservers
  become: yes
  vars_files:
    -~/devopsLabs/ansible/ansible-apache/secrets.yml
  tasks:
    - name: Fix apt repository sources
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse

    - name: Remove duplicate apt configurations
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present
        update_cache: yes


